#ifndef __PWMSS_H__
#define __PWMSS_H__
#include "util.h"

#define PWMSS_SYSCONFIG_OFFS  				0x4
#define PWMSS_SYSCONFIG_STANDBY_OFFS		4
#define PWMSS_SYSCONFIG_STANDBY_MASK		BIT_MASK(5,4)
#define PWMSS_SYSCONFIG_STANDBY_NONE		(0x1 << PWMSS_SYSCONFIG_STANDBY_OFFS)
#define PWMSS_SYSCONFIG_STANDBY_SMART		(0x2 << PWMSS_SYSCONFIG_STANDBY_OFFS)
#define PWMSS_SYSCONFIG_IDLE_OFFS			2
#define PWMSS_SYSCONFIG_IDLE_MASK			BIT_MASK(3,2)
#define PWMSS_SYSCONFIG_IDLE_NONE			(0x1 << PWMSS_SYSCONFIG_IDLE_OFFS)
#define PWMSS_SYSCONFIG_IDLE_SMART			(0x2 << PWMSS_SYSCONFIG_IDLE_OFFS)

#define PWMSS_CLKCONFIG_OFFS  				0x8
#define PWMSS_CLKCONFIG_EPWM_STOP     		BIT(9)
#define PWMSS_CLKCONFIG_EPWM_START    		0
#define PWMSS_CLKCONFIG_EPWM_EN  			BIT(8)
#define PWMSS_CLKCONFIG_EPWM_DIS 			0

#define PWMSS_CLKSTATUS_OFFS  				0xC
#define PWMSS_CLKSTATUS_EPWM_STOP     		BIT(9)
#define PWMSS_CLKSTATUS_EPWM_EN  			BIT(8)


#endif
